config/routes.rb
Pollster::Application.routes.draw do

  resources :polls do
    resources :questions
  end

  match '/:link' => 'polls#show', :as => :admin_link
  root :to => 'polls#new'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :name, :admin_link
  has_many :questions

  def set_admin_link
    self.admin_link = new_link
  end

  private

  def new_link
    link = generate_random until Poll.find_by_admin_link(link) == nil
    link
  end

  def generate_random
    rand(36**10).to_s(36)
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content
  belongs_to :poll
  has_many :responses
end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :content
  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
    @polls = Poll.all
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(params[:poll])
    @poll.set_admin_link
    @question = Question.new
    if @poll.save
      render 'edit'
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @question = Question.new
    if params[:id]
      @poll = Poll.find(params[:id])
    elsif params[:link]
      @poll = Poll.find_by_admin_link(params[:link])
      render 'edit'
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @poll = Poll.find(params[:poll_id])
    @questions = Question.where(:poll_id => @poll.id)
  end

  def new
    @poll = Poll.find(params[:poll_id])
    @question = Question.new
  end

  def create
    @poll = Poll.find(params[:poll_id])
    @question = Question.new(params[:question])
    @question.poll_id = @poll.id
    if @question.save
      redirect_to admin_link_path(@poll.admin_link)
    else
      render :partial => 'form', :question => @question
    end
  end

  def edit
    @question = Question.find(params[:id])
    @poll = Poll.find(params[:poll_id])
  end

  def update
    @poll = Poll.find(params[:poll_id])
    @question = Question.find(params[:id])
    @question.update_attributes(params[:question])
    redirect_to admin_link_path(@poll.admin_link)
  end

  def destroy
    question = Question.find(params[:id])
    poll = Poll.find(params[:poll_id])
    question.destroy
    redirect_to admin_link_path(poll.admin_link)
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polls/_public_view.html.erb
<h1><%= @poll.name %></h1>
<h4>Poll URL: <%= link_to @poll.id, @poll %></h4>

app/views/polls/edit.html.erb
Admin page

<%= render '/polls/public_view' %>
<h4>Admin URL: <%= link_to @poll.admin_link, admin_link_path(@poll.admin_link) %></h4>
<% @poll.questions.each do |question| %>
  <%= question.content %>
  <%= link_to 'Edit', edit_poll_question_path(@poll, question) %>
  <%= link_to 'Destroy', poll_question_path(@poll, question), method: :delete, data: { confirm: 'Are you sure?'} %>
  <br>
<% end %>
<%= render '/questions/form' %>

app/views/polls/index.html.erb
<% @polls.each do |poll| %>
  <%= link_to poll.name, poll %><br>
<% end %>

<%= link_to 'New Poll', new_poll_path(Poll.new) %><br>

app/views/polls/new.html.erb
<h1>Create a new poll</h1>

<%= form_for @poll do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/polls/show.html.erb
<%= render '/polls/public_view' %>

<%= render @poll.questions %>

app/views/questions/_form.html.erb
<%= form_for [@poll, @question] do |f| %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/questions/_new.html.erb
<%= form_for [@poll, @question = Question.new] do |f| %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/questions/_question.html.erb
<%= question.content %><br>

app/views/questions/edit.html.erb
<%= render 'form', :poll => @poll, :question => @question %>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
  <%= question.content %><br>
<% end %>

app/views/questions/new.html.erb
<%= form_for [@poll, @question] do |f| %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>